language: node_js
node_js:
  - "7"
notifications:
  email:
    - brandonyoyoslade@gmail.com
    - jfurtado@student.neumont.edu
    - keima.ayasaki@gmail.com
before_script:
  - cd agile-game
  - yarn
script:
  - yarn travis -s
